name: pre-commit

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Run pre-commit checks
              uses: j178/prek-action@v2
              with:
                extra-args: '--all-files'
